### ISSUE TITLE
Add hover effect

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#1]
add hover effect to [get_involved](https://github.com/Virtual4087/Tree2Hope/blob/0798eda3a8c32f4d677d8824e706690e16ac4b31/index.html#L81C1-L85C11) section.

The hover effect shouldn't be too flashy just keep the effect minimal.

**Comment by Kiran-Alex** [comment]
please assign this issue to me i would like to work on this

**Comment by Virtual4087** [comment]
@Kiran-Alex this is a small issue so i'll be merging the first pr

**Comment by Ritish134** [comment]
Created the pull request #4
