### ISSUE TITLE
want to bold heading tag text for better appearence

### ISSUE THREAD

**Issue by pra9patil** [Virtual4087/Tree2Hope#103]
Hey @Virtual4087 I want to bold text which in heading 

## Before
![Screenshot (101)](https://github.com/Virtual4087/Tree2Hope/assets/130309887/262bf88e-0360-4332-9b42-8669dd1bcf9b)

## After
![Screenshot (100)](https://github.com/Virtual4087/Tree2Hope/assets/130309887/db5b8f49-cfa6-473f-b7ce-7f77c6caed2a)

**Comment by pra9patil** [comment]
using simple html b tag will  you plz assign me this issue

**Comment by Virtual4087** [comment]
Do it
