### ISSUE TITLE
Change About Us page design

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#107]
The about us page doesn't blend in with the background. Change the background where the text is written. Maybe you could give it a blurry glass effect. 

Note: Don't wait to get assigned. The first pr that looks good gets merged. Also don't forget to add a ss of your work.

**Comment by shreyanshi-bhatt** [comment]
I am interested in contributing. Would you like me to work on this issue or wait for another issue to open? @Virtual4087
