### ISSUE TITLE
Change "We haven't added this feature yet" design

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#108]
When you click on "Just $1 plants a tree" button, a popup like this appears:
![image](https://github.com/user-attachments/assets/96f6f635-dbad-43a2-9252-ec308d3f56b8)

Change the UI of the popup box to match with the website and also change the text to  "This feature has not been added yet"

Note: Don't wait to get assigned. The first pr that looks good gets merged. Also don't forget to add a ss of your work.

**Comment by MUDITJAINN** [comment]
@Virtual4087 Please assign this issue to me under hacktoberfest2024.

**Comment by Virtual4087** [comment]
@MUDITJAINN I have said in the note that you don't need to get assigned to it since it is a very small issue.  The issue has already been resolved but feel free to create new ones.
