### ISSUE TITLE
Add scroll effect to the Navbar

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#129]
The navbar should only appear after the user scrolls past the cover page and reaches "Where we plant" section. The dark background of the nav bar should also be added only then. Otherwise the Navbar should be where it is without the dark background.

**Comment by swarupn17** [comment]
Hey @Virtual4087 I can do this task please can you assign it to me.
Thanks !

**Comment by Virtual4087** [comment]
@swarupn17 done
