### ISSUE TITLE
Social Media Icons inconsistent across different screen sizes

### ISSUE THREAD

**Issue by prashantsingh181** [Virtual4087/Tree2Hope#141]
Social Media Icons are overflowing in smaller screen sizes. I would like to fix it.
<img width="428" alt="Screenshot 2024-10-12 at 1 18 01 PM" src="https://github.com/user-attachments/assets/fd1bfd93-920a-4a83-a55f-f40ee81e963f">

**Comment by Virtual4087** [comment]
@prashantsingh181 done

**Comment by Virtual4087** [comment]
This issue has been resolved.
