### ISSUE TITLE
"WHERE WE PLANT" heading not visible

### ISSUE THREAD

**Issue by prashantsingh181** [Virtual4087/Tree2Hope#142]
"WHERE WE PLANT" heading is not visible in smaller screen sizes due to contrast with the background. I would like to work on it.
<img width="374" alt="Screenshot 2024-10-12 at 1 24 59 PM" src="https://github.com/user-attachments/assets/3609050c-3f48-46c1-8d5a-9aa8a8b4f981">

**Comment by Virtual4087** [comment]
@prashantsingh181 assigned

**Comment by prashantsingh181** [comment]
#147
