### ISSUE TITLE
Update copyright year and segregate Javascript code

### ISSUE THREAD

**Issue by Maaz-Code** [Virtual4087/Tree2Hope#144]
Hello @Virtual4087, 
I would like to contribute to this project as part of **Hacktoberfest 2024**. I am suggesting two changes:

- Update the copyright year in the footer to 2024. Currently, it's 2023:
![image](https://github.com/user-attachments/assets/b0929744-5c42-4c7f-b9e7-9ba4010c88a7)

- Move all the javascript code to respective script files for better segregation and reduce code debt in HTML files.

**Comment by Virtual4087** [comment]
@Maaz-Code That would be really helpful but please check everything is working as they were originally before creating a pr.

**Comment by Virtual4087** [comment]
@Maaz-Code I've assigned this to you under hacktoberfest
