### ISSUE TITLE
Missing Footer Section in About Page

### ISSUE THREAD

**Issue by ankitjhagithub21** [Virtual4087/Tree2Hope#145]
![image](https://github.com/user-attachments/assets/d64f6206-a27d-4d9e-928d-a36cd1a79c89)

I would like to work on resolving the issue where the footer section is missing from the About page. I will ensure the footer is added and styled correctly.

**Comment by Virtual4087** [comment]
@ankitjhagithub21 I've assigned you

**Comment by Phanty78** [comment]
Hello, can you assign me too on this task ?

**Comment by Virtual4087** [comment]
@Phanty78 Since @ankitjhagithub21 has been idle for 4 days I've assigned it to you

**Comment by Phanty78** [comment]
@virtual4087 , job is done.

**Comment by Virtual4087** [comment]
Thanks @Phanty78 I've merged it.
