### ISSUE TITLE
Making A contact us and about page on index html

### ISSUE THREAD

**Issue by Deepankar1484** [Virtual4087/Tree2Hope#152]
Hey @Maaz-Code & @Virtual4087  ,
I have found this as a issue because all the other pages like donate, events are showing on the same page but the about is on a different page.
And the footer is set as a Contact us page.

Assign me the task with a hacktober fest label so that i can contribute to this amazing project.

**Comment by Virtual4087** [comment]
@Deepankar1484 I think about us page in another page is fine
