### ISSUE TITLE
[BUG]: Styling of Navbar is not proper

### ISSUE THREAD

**Issue by Prayash007** [Virtual4087/Tree2Hope#153]
While scrolling, the page elements overlap with navLinks.

![image](https://github.com/user-attachments/assets/80c58024-6cf5-4a23-bcce-ccdae9848e60)

**Comment by Prayash007** [comment]
@Virtual4087 Please assign me this issue!

**Comment by Virtual4087** [comment]
@Prayash007 How do you plan on solving this?

**Comment by Virtual4087** [comment]
@Prayash007 sounds good I've assigned you
