### ISSUE TITLE
Hamburger not clickable

### ISSUE THREAD

**Issue by prashantsingh181** [Virtual4087/Tree2Hope#165]
In mobile view, when header is visible along with hamburger, The hamburger icon is not clickable due to less z-index.
I would like to work on this issue. Can you please assign me this?
<img width="463" alt="Screenshot 2024-10-20 at 12 33 38 AM" src="https://github.com/user-attachments/assets/c0190af8-cf07-4eab-b3f9-9e576a69c539">

**Comment by Bamof25th** [comment]
Please /assign i want to fix it !

**Comment by Virtual4087** [comment]
@prashantsingh181 I've assigned it to you
