### ISSUE TITLE
Add a progress bar at the bottom

### ISSUE THREAD

**Issue by Anurag519Narula** [Virtual4087/Tree2Hope#166]
Want to add a progress bar which moves as you scroll, it is implemented on many sites like it shows you how much page you have scrolled. If you feel this issue is good, please mark this issue as hacktoberfest and assign me this task, @Virtual4087 , thanks!
![progress bar](https://github.com/user-attachments/assets/1c396c89-3b7d-4546-b214-fcf0c28eb8a3)

**Comment by Virtual4087** [comment]
@Anurag519Narula That sounds really good. I've assigned you.
