### ISSUE TITLE
Navbar related in responsiveness

### ISSUE THREAD

**Issue by DHRUVKAPOOR07** [Virtual4087/Tree2Hope#176]
I see that when i start decreasing the pixels of screen its responsiveness is shown and with a hamburger icon but i see when i click on it it looks very simple. I decide to make an slider from right to left when any person click on that icon.

**Comment by Virtual4087** [comment]
@DHRUVKAPOOR07 I have assigned it to you

**Comment by Virtual4087** [comment]
I've already assigned it to you. Waiting for your pr :)
