### ISSUE TITLE
[feat[ [bug[: Transition to WebP Format and Replace PNG Images with Icons

### ISSUE THREAD

**Issue by purnasth** [Virtual4087/Tree2Hope#18]
# Issue Title: Transition to WebP Format and Replace PNG Images with Icons

## Issue Description:
I propose a modification to the existing project that involves transitioning from using PNG images to the more efficient WebP format for image assets. Additionally, I suggest replacing .png images with vector icons wherever possible. These adjustments will enhance the project's performance and streamline image management.

## Proposed Changes:
1. **Image Format Transition**: Replace existing .png images with WebP images. WebP is a modern and efficient image format known for its smaller file size and better compression, resulting in faster loading times.

2. **Icon Integration**: Wherever feasible, replace .png images with vector icons. Vector icons are highly scalable and reduce the dependency on multiple image files.

## Rationale:
The transition to WebP format and the replacement of .png images with icons offer several advantages:

### Improved Performance:
WebP images enhance loading speed and overall project performance, making it well-suited for web applications.

### Scalability and Reduced File Size:
Vector icons are highly scalable and have smaller file sizes compared to bitmap images, contributing to efficient project asset management.

## Attachments

![image](https://github.com/Virtual4087/Tree2Hope/assets/107195487/201318fe-9214-451a-a289-f012ac3468cb)

## Additional Information (if available):
If specific guidelines or steps are required for implementing these changes and if any additional information is needed, please provide guidance. I am dedicated to delivering these enhancements effectively.

Thank you for considering this issue for improving the project's performance and image management.

**Comment by Virtual4087** [comment]
Hi @purnasth, Thanks for raising such an important issue. I agree that the current images might be affecting the website speed, and the idea of transitioning to WebP and incorporating vector images sounds like a reasonable solution.

Regarding guidelines, feel free to make the changes you think will enhance the site's performance. If there are any images that can't be converted, use your discretion to select suitable replacements (except the logo).

Let me know if you need further details or encounter any issues.
