### ISSUE TITLE
Enable Contact Us link

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#2]
Current behavior:
The contact us link in the navbar does nothing right now. 

Expected behavior:
When a user clicks on the link they should be taken to the footer section of the page without reloading. Additionally the form in the footer section should also be activated. For this you can just make the input box for email active.

**Comment by Ayush-gupta-dev** [comment]
I would like to contribute in this repository, please assign this issue to me @Virtual4087

**Comment by AmosBlack** [comment]
Hey @Virtual4087, can i contribute to this repository ?

**Comment by Virtual4087** [comment]
Sure you're welcome to try

**Comment by AmosBlack** [comment]
created pr for same
