### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#20]
As of now, the readme only contains a short description of the website. Add stuff like hactoberfest contribution, basic contribution rules, small setup guide and style them properly. You can also add other things such as license, contributors profile's if you wish.

**Comment by KaneshiroKeola** [comment]
Hello @Virtual4087 
May I contribute to this repo by adding a contributors list and some descriptors of the website?

**Comment by Virtual4087** [comment]
@KaneshiroKeola Sure i've assigned this to you.

**Comment by KaneshiroKeola** [comment]
Thankyou @Virtual4087 :)
