### ISSUE TITLE
Add "About Us" page

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#21]
Create a separate html file for about us. The styling should be similar to index.html and  it should contain a detailed description of the website. The content inside the page doesn't matter a lot since i can change it anytime but the design should look good. You can also add quotes and all the other stuff that are found in a basic about us page.

Create a white box on top of the cover page and add your text in it. (Recommended)

**Comment by awsmdeep** [comment]
hi @Virtual4087 i hope you are doing well , can you assign me this work

**Comment by Virtual4087** [comment]
@awsmdeep done

**Comment by Gokulr08** [comment]
Bro can you assign this work to me? I will be happy to contribute

**Comment by Virtual4087** [comment]
@Gokulr08 it's already assigned but you are free to open new issues.

**Comment by Virtual4087** [comment]
Hey @Gokulr08 are you still willing to work on this? If yes i'll assign it to you.

**Comment by awsmdeep** [comment]
@Virtual4087 can i get more time , if yes please assign me again

**Comment by Virtual4087** [comment]
@awsmdeep you are already assigned to this so you can keep on working.

**Comment by Gokulr08** [comment]
i just given a pull request.. can you tell me what changes should i do? this is my first contribute

**Comment by Virtual4087** [comment]
@Gokulr08 I've reviewed your pr and already left a comment. Please refrain from discussing matters about you pr in the issue comments from now on.

**Comment by laurenziello** [comment]
@Virtual4087 found this message on hacktoberfest site "Your PR/MR was submitted to a repository that is not participating in Hacktoberfest. Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR/MR."

**Comment by Virtual4087** [comment]
@laurenziello I've added the required labels in the repo. It might take a while. All the prs you made to this repo will still count once it gets participated.
