### ISSUE TITLE
Add responsiveness

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#22]
There is a lot of overlapping between contents on smaller screens in the website. Make the site responsive so that nothing gets overlapped when the screen size is decreased.

**Comment by 08Uzair** [comment]
Please Assign this project to me

**Comment by Virtual4087** [comment]
@08Uzair done

**Comment by 08Uzair** [comment]
ok

**Comment by JanumalaAkhilendra** [comment]
Please Assign this project to me, if it is still open.

**Comment by Virtual4087** [comment]
@JanumalaAkhilendra  The task has been assigned, but feel free to open new issues if you have additional suggestions or concerns. Your input is always welcome.
