### ISSUE TITLE
Fix mobile view

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#39]
On mobile view the content of the website is overflowing horizontally which makes the page horizontally scrollable.It's probably because of social media icons in the footer that don't wrap when the screen size is decreased . 

To check this issue goto inspect > mobile view > select any small screen size

You should be able to see some white space at the right part of your screen.

**Comment by 08Uzair** [comment]
Please assign this to me

**Comment by Virtual4087** [comment]
@08Uzair done try to do it ASAP
