### ISSUE TITLE
Activate donate now button

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#40]
Clicking on donate now should open a white popup that says "We haven't added this feature yet". You can achieve this using JavaScript.

**Comment by Arceen** [comment]
Hey @Virtual4087 ! Can you assign this to me please?

**Comment by Virtual4087** [comment]
@Arceen done Please submit ASAP

**Comment by Arceen** [comment]
Hey @Virtual4087 ! Can you check the PR to see if it's ok. Thanks!
