### ISSUE TITLE
Update Contributors list

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#45]
Clicking on contributors profile in readme should take the user the that specific contributors profile.

Note:- This issue will not be assigned, the first one to submit their pr will get it merged.

**Comment by dakshsinghrathore** [comment]
@Virtual4087 Kindly assign this issue to me !

**Comment by dakshsinghrathore** [comment]
@Virtual4087 How about if we use the tool: https://github.com/all-contributors/cli to show all the contributors, hopefully in the future we can have a lot of them 😄 !!

Something like this 👇🏽

![image](https://github.com/Virtual4087/Tree2Hope/assets/115932772/be7debc2-8200-4ed4-897f-48649e139e1a)

**Comment by Virtual4087** [comment]
@dakshsinghrathore Great idea! Would you like to work on it?

**Comment by dakshsinghrathore** [comment]
yes @Virtual4087
