### ISSUE TITLE
Fix gapping

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#5]
Everything looks really congested right now. Fix the gap between all the sections in the website.

**Comment by srivastav2006** [comment]
i can do it 
assign this to me

**Comment by Virtual4087** [comment]
@srivastav2006 looking forward to your pr

**Comment by AmosBlack** [comment]
Could you explain the issue in a little bit more detail.

**Comment by Virtual4087** [comment]
@AmosBlack the webpage looks alright on bigger screen but on smaller screen it looks very congested. There should be proper spacing between different sections of the webpage.

**Comment by AmosBlack** [comment]
Alright, I'll do it. Please assign it to me.
