### ISSUE TITLE
Changing the font color of the texts in get_involved section

### ISSUE THREAD

**Issue by Shreshth-Srivastava** [Virtual4087/Tree2Hope#51]
Hey there, I would like to improve the styling of the texts in get_involved section so please assign this issue to me under "hacktoberfest" label.

From:

![Current](https://github.com/Virtual4087/Tree2Hope/assets/134348598/365f4520-9cfb-473b-948d-ec9342d81c99)

To:

![My_Idea](https://github.com/Virtual4087/Tree2Hope/assets/134348598/eeb48122-2c9d-4996-8c96-be56efbbbfa9)

**Comment by Virtual4087** [comment]
@Shreshth-Srivastava done but i think it would look better if you match it with the color we get when hovering over links in the navbar.

**Comment by Shreshth-Srivastava** [comment]
Understood

**Comment by Shreshth-Srivastava** [comment]
I have modified the style of the texts as you wanted and here is a preview. If this is alright, then tell me and I will create a pull request for this issue.
![Preview](https://github.com/Virtual4087/Tree2Hope/assets/134348598/e1599f1e-7fba-44b6-9be6-5e2d94fc60c1)

**Comment by Virtual4087** [comment]
You are right, the former one looks better. Go with it.

**Comment by Shreshth-Srivastava** [comment]
Alright then

**Comment by Shreshth-Srivastava** [comment]
Done, I have created a pull request for this issue, please review it.
