### ISSUE TITLE
Fix footer on mobile view

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#60]
Social media part in the footer overflows on mobile view.

**Comment by mohtasheem135** [comment]
Please Assign this to me.....I can work on this

**Comment by Virtual4087** [comment]
@mohtasheem135 done. Try to do it ASAP!

**Comment by mohtasheem135** [comment]
starting the work right away

**Comment by mohtasheem135** [comment]
I have created the pull request please add the tag of hactoberfest

**Comment by Virtual4087** [comment]
done @mohtasheem135
