### ISSUE TITLE
Center links in the footer

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#65]
The quick links in the footer are too far apart. Adjust the gap between them. Keep in mind that the design should be responsive.

Note:- You don't need to wait to be assigned, open a pr with proper title and description and a short screencast showcasing your changes. I'll accept the first pr.

**Comment by mohtasheem135** [comment]
You can assign this to me....I can do this

**Comment by Virtual4087** [comment]
@mohtasheem135 done. Try doing it ASAP

**Comment by Shreshth-Srivastava** [comment]
@Virtual4087 
Hey there, I have made the required changes and I am uploading two previews showcasing two different spacing styles. Tell me which one you want and I will create a pull request for this issue. If both them is not satisfactory then tell me what I can improve and I will make the appropriate changes.

From:

![Current](https://github.com/Virtual4087/Tree2Hope/assets/134348598/78d02b02-7526-4713-b0af-452a9174d002)

To:

Preview-1:

![Preview](https://github.com/Virtual4087/Tree2Hope/assets/134348598/007cb096-e917-47eb-bfa0-e4eccd5b2b77)

Preview-2: 

![Preview_2](https://github.com/Virtual4087/Tree2Hope/assets/134348598/0ac37702-2e5e-4b45-99c1-b964fde56a43)

**Comment by Virtual4087** [comment]
@Shreshth-Srivastava 1st one looks good, you can apply that.

**Comment by Shreshth-Srivastava** [comment]
@Virtual4087 
I have created a pull request for this issue, please review it.
