### ISSUE TITLE
Issue with Contact Us Link  in the header Section

### ISSUE THREAD

**Issue by Shubhangam333** [Virtual4087/Tree2Hope#76]
Hey, 

I can see the text wrapping issue with contact us link on the header section,
Let me Know if I can fix this.

**Comment by Virtual4087** [comment]
@Shubhangam333 go ahead

**Comment by Shubhangam333** [comment]
#77  Raised this PR, Kindly check and merge it. Thanks for providing me this oppurtunity

**Comment by Virtual4087** [comment]
@Shubhangam333 done. Feel free to raise more issues.
