### ISSUE TITLE
Footer Contents Misaligned and Congested

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#9]
The contents in the footer section of the repository are currently misaligned and congested, resulting in a bad UX. The lack of proper spacing makes it difficult to distinguish between different elements in the footer.

**Comment by rishika-g31** [comment]
please assign me this issue.

**Comment by Virtual4087** [comment]
@rishika-g31 done

**Comment by rishika-g31** [comment]
please merge this pull request under hactoberfest, or tell me if their is some other requirements or changes to be done.
