### ISSUE TITLE
Add relevant text in about us page

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#93]
The text in about us page is irrelevant. Change it to match our website's motto i.e. to plant trees as a charity website.

**Comment by abhinavs1920** [comment]
I am working on this issue please assign it to me

**Comment by manan18** [comment]
Your project looks interesting and innovative , I would really like to work on it.
Can you please assign me this issue?

**Comment by manan18** [comment]
Hello @Virtual4087, I initiated a Pull Request #96 , but it shows merging is blocked. Can you please look into the issue?

**Comment by Virtual4087** [comment]
@manan18 That's nothing to worry about

**Comment by manan18** [comment]
Ok then, I've made some changes. Please review PR #96 .
