### ISSUE TITLE
Add links to the countries 

### ISSUE THREAD

**Issue by Virtual4087** [Virtual4087/Tree2Hope#94]
Clicking on the country images in "Where we plant" section should redirect the user to that country's wiki page. Set the target to blank so it opens in a new tab. You should also attach a short screencast of the changes you made in your pr.

**Comment by manan18** [comment]
Your project looks interesting and innovative , I would really like to work on it. 
Can you please assign me this issue?

**Comment by Shashankpantiitbhilai** [comment]
I would like to contribute several countries ,please assign this to me
