### ISSUE TITLE
Want to add new card in where we plant page to maintain consistency in web 

### ISSUE THREAD

**Issue by pra9patil** [Virtual4087/Tree2Hope#95]
Hey @Virtual4087 sir
I go through your website and I like it and want to contribute in it 

I as notice in your website 
where we plant page I feel there is in consistency so I want to add some extra card there to maintan it

so will you please assign me this issue please

**Comment by Virtual4087** [comment]
@pra9patil can you be more precise about what changes you want to make?

**Comment by pra9patil** [comment]
![Screenshot (95)](https://github.com/Virtual4087/Tree2Hope/assets/130309887/b8cbd006-3e11-4d6e-8923-7314a7357a4b)

**Comment by Virtual4087** [comment]
@pra9patil please explain a little more.

**Comment by pra9patil** [comment]
Yes my laptop's net get disconnected sorry for inconvenience
So sir I as you see in Screenshot  in last row there is only one card it looks very inconsistent so I want to add 3 more cards there so it will feel consistent and better
What is your thoughts on it sir

**Comment by Virtual4087** [comment]
@pra9patil Even if you add 3 more cards they'll eventually get wrapped for users on smaller screen sizes. So i think a better alternative would be centering the last country image. If you wanna do that feel free to open another issue.
