### ISSUE TITLE
Add hover effect to "Our goals" cards to improve user experience

### ISSUE THREAD

**Issue by ShrujanaReddy** [Virtual4087/Tree2Hope#99]
<img width="715" alt="image" src="https://github.com/Virtual4087/Tree2Hope/assets/130744023/a2f42991-7ef3-4c95-a8ad-750307f06e49">

**Comment by ShrujanaReddy** [comment]
Hey ! Can you assign me this issue.

**Comment by Virtual4087** [comment]
While you're at it, manage the vertical gapping as well.

**Comment by ShrujanaReddy** [comment]
> While you're at it, manage the vertical gapping as well.

Sure!

**Comment by ShrujanaReddy** [comment]
@Virtual4087 Are there any changes you want to suggest?
